version: "3.1"

services:
  postgresql:
    image: docker.io/bitnami/postgresql:14
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - "postgresql_data:/bitnami/postgresql"

  keycloak:
    image: docker.io/bitnami/keycloak:16
    depends_on:
      - postgresql
    environment:
      - KEYCLOAK_EXTRA_ARGS=-Dkeycloak.profile.feature.scripts=enabled
      - KEYCLOAK_EXTRA_ARGS=-Dkeycloak.profile.feature.upload_scripts=enabled
    ports:
      - "9080:8080"

volumes:
  postgresql_data:
    driver: local
